describe('Search Duckduckgo', () => {
	beforeEach(async () => {
		await page.goto('https://www.bing.com');
	});

	it('should be titled "Google"', async () => {
		//Google search
		await page.goto('https://www.duckduckgo.com');
		var element = await page.$('[name="q"]');
		await element.click();
		await element.type('Google');
		await Promise.all([
			page.keyboard.press('Enter'),
			page.waitForNavigation()
		]);
		var title = await page.title();
		expect(title).toEqual('Google at DuckDuckGo', 'Expected page title is incorrect!');
		const firstResult = await page.$('#r1-0 h2')
		await firstResult.click();
		await page.waitForTimeout(2000);
		var googleSerachField = await page.$('[name="q"]');
		await googleSerachField.click();
		await googleSerachField.type("Hello");
		await page.keyboard.press('Enter');
		await Promise.all([
			page.waitForNavigation()
		]);
		var googleSerachTitle = await page.title();
		expect(googleSerachTitle).toEqual('Hello - Google Search', 'Google -Expected page title is incorrect!');
		//Lambdatest sample app test
		await page.goto('https://lambdatest.github.io/sample-todo-app/');
		await page.waitForTimeout(5000);
		await page.click('body > div > div > div > ul > li:nth-child(1) > input');
		await page.click('body > div > div > div > ul > li:nth-child(2) > input');
		await page.click('body > div > div > div > ul > li:nth-child(3) > input');
		await page.click('body > div > div > div > ul > li:nth-child(4) > input');
		await page.click('body > div > div > div > ul > li:nth-child(5) > input');
		await page.type('#sampletodotext', 'Hypertest LambdaTest');
		await page.click('#addbutton');
		await page.click('body > div > div > div > ul > li:nth-child(6) > input');
		await page.type('#sampletodotext', 'Hypertest LambdaTest');
		await page.click('#addbutton');
		await page.click('body > div > div > div > ul > li:nth-child(7) > input');
		//Puppeteer site
		page.setViewport({ width: 1920, height: 1080 });
		await page.goto('https://pptr.dev/');
		await page.click('[href="/guides/"]');
		await page.click('[href="/api/"]');
		await page.waitForXPath('//h1[contains(text(), "API Reference")]'); 
		expect(await page.title()).toEqual('API Reference | Puppeteer');
		await page.click('[href="/api/puppeteer.accessibility"]');
		await page.waitForXPath('//h1[contains(text(), "Accessibility class")]');
		expect(await page.title()).toEqual('Accessibility class | Puppeteer');
		await page.click('[href="/api/puppeteer.accessibility.snapshot"]');
		await page.waitForXPath('//h1[contains(text(), "Accessibility.snapshot() method")]');
		expect(await page.title()).toEqual('Accessibility.snapshot() method | Puppeteer');
		await page.click('[href="/api/puppeteer.actionresult"]');
		await page.waitForXPath('//h1[contains(text(), "ActionResult type")]');
		expect(await page.title()).toEqual('ActionResult type | Puppeteer');
		await page.click('[href="/api/puppeteer.awaitable"]');
		await page.waitForXPath('//h1[contains(text(), "Awaitable type")]');
		expect(await page.title()).toEqual('Awaitable type | Puppeteer');
		await page.click('[href="/api/puppeteer.boundingbox.height"]');
		await page.waitForXPath('//h1[contains(text(), "BoundingBox.height property")]');
		expect(await page.title()).toEqual('BoundingBox.height property | Puppeteer');
		await page.click('[href="/api/puppeteer.boundingbox"]');
		await page.waitForXPath('//h1[contains(text(), "BoundingBox interface")]');
		expect(await page.title()).toEqual('BoundingBox interface | Puppeteer');
		await page.goto('https://pptr.dev/');
		await page.click('[href="/api/"]');
		await page.click('[href="/api/puppeteer.boundingbox.width"]');
		await page.waitForXPath('//h1[contains(text(), "BoundingBox.width property")]');
		expect(await page.title()).toEqual('BoundingBox.width property | Puppeteer');
		await page.click('[href="/api/puppeteer.boxmodel.border"]');
		await page.waitForXPath('//h1[contains(text(), "BoxModel.border property")]');
		expect(await page.title()).toEqual('BoxModel.border property | Puppeteer');
		await page.click('[href="/api/puppeteer.boxmodel.content"]');
		await page.waitForXPath('//h1[contains(text(), "BoxModel.content property")]');
		expect(await page.title()).toEqual('BoxModel.content property | Puppeteer');
		await page.click('[href="/api/puppeteer.boxmodel.height"]');
		await page.waitForXPath('//h1[contains(text(), "BoxModel.height property")]');
		expect(await page.title()).toEqual('BoxModel.height property | Puppeteer');
		await page.click('[href="/api/puppeteer.boxmodel.margin"]');
		await page.waitForXPath('//h1[contains(text(), "BoxModel.margin property")]');
		expect(await page.title()).toEqual('BoxModel.margin property | Puppeteer');
		await page.click('[href="/api/puppeteer.boxmodel"]');
		await page.waitForXPath('//h1[contains(text(), "BoxModel interface")]');
		expect(await page.title()).toEqual('BoxModel interface | Puppeteer');
		await page.click('[href="/api/puppeteer.boxmodel.padding"]');
		await page.waitForXPath('//h1[contains(text(), "BoxModel.padding property")]');
		expect(await page.title()).toEqual('BoxModel.padding property | Puppeteer');
		await page.click('[href="/api/puppeteer.boxmodel.width"]');
		await page.waitForXPath('//h1[contains(text(), "BoxModel.width property")]');
		expect(await page.title()).toEqual('BoxModel.width property | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.browsercontexts"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.browserContexts() method")]');
		expect(await page.title()).toEqual('Browser.browserContexts() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.close"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.close() method")]');
		expect(await page.title()).toEqual('Browser.close() method | Puppeteer');	
		await page.goto('https://pptr.dev/');
		await page.click('[href="/api/"]');	
		await page.click('[href="/api/puppeteer.browser.createincognitobrowsercontext"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.createIncognitoBrowserContext() method")]');
		expect(await page.title()).toEqual('Browser.createIncognitoBrowserContext() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.defaultbrowsercontext"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.defaultBrowserContext() method")]');
		expect(await page.title()).toEqual('Browser.defaultBrowserContext() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.disconnect"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.disconnect() method")]');
		expect(await page.title()).toEqual('Browser.disconnect() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.isconnected"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.isConnected() method")]');
		expect(await page.title()).toEqual('Browser.isConnected() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser"]');
		await page.waitForXPath('//h1[contains(text(), "Browser class")]');
		expect(await page.title()).toEqual('Browser class | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.newpage"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.newPage() method")]');
		expect(await page.title()).toEqual('Browser.newPage() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.pages"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.pages() method")]');
		expect(await page.title()).toEqual('Browser.pages() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.process"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.process() method")]');
		expect(await page.title()).toEqual('Browser.process() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.target"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.target() method")]');
		expect(await page.title()).toEqual('Browser.target() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.targets"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.targets() method")]');
		expect(await page.title()).toEqual('Browser.targets() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.useragent"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.userAgent() method")]');
		expect(await page.title()).toEqual('Browser.userAgent() method | Puppeteer');
		await page.click('[href="/api/puppeteer.browser.version"]');
		await page.waitForXPath('//h1[contains(text(), "Browser.version() method")]');
		expect(await page.title()).toEqual('Browser.version() method | Puppeteer');
	});
});
